---
# RedHat tasks file for ansible-role-suricata

- name: "Install Suricata (yum)"
  yum:
    name: "suricata"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Install Suricata (dnf)"
  shell: dnf install -y --nobest suricata
  args:
    warn: false
  register: dnf_suricata_install
  changed_when: "'Nothing to do' not in dnf_suricata_install.stdout"
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Install Suricata (apt)"
  apt:
    name: "suricata"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'apt'
