---
# Lookup tasks file for ansible-role-suricata

- name: "Set fact for version (Production)"
  set_fact:
    version: "7.0"
  when:
    - target == "production"
    - ansible_distribution_major_version >= '8'

- name: "Set fact for version (Legacy)"
  set_fact:
    version: "6.0"
  when:
    - target == "production"
    - ansible_distribution_major_version <= '7'

- name: "Set fact for version (Development)"
  set_fact:
    version: "devel"
  when:
    - target == "development"

- name: "Check if {{ suricata_group }} group exists"
  getent:
    database: group
    key: "{{ suricata_group }}"
  register: group_check
  #failed_when: group_check.failed
  ignore_errors: true
  changed_when: false

- name: "Fail if {{ suricata_group }} group does not exist"
  fail:
    msg: "Group '{{ suricata_group }}' does not exist on this host."
  when: group_check is failed

- name: "Check if {{ suricata_user }} user exists"
  getent:
    database: passwd
    key: "{{ suricata_user }}"
  register: user_check
  failed_when: user_check.failed
  changed_when: false

- name: "Fail if {{ suricata_user }} user does not exist"
  fail:
    msg: "User '{{ suricata_user }}' does not exist on this host."
  when: user_check is failed

- name: "Collect stats of archive_file"
  stat:
    path: "{{ archive_file }}"
  register: output
  when:
    - archive_file is defined
    - archive_file is string

- name: "Set fact for restore if archive_file exists"
  set_fact:
    restore: true
  when:
    - archive_file is defined
    - archive_file is string
    - output.stat.exists
    - output.stat.isreg
