---
# Lookup tasks file for ansible-role-suricata

- name: "Set fact for version (Production)"
  set_fact:
    version: "7.0"
  when:
    - target == "production"
    - ansible_distribution_major_version >= '8'

- name: "Set fact for version (Legacy)"
  set_fact:
    version: "6.0"
  when:
    - target == "production"
    - ansible_distribution_major_version <= '7'

- name: "Set fact for version (Development)"
  set_fact:
    version: "devel"
  when:
    - target == "development"

- name: "Collect stats of archive_file"
  stat:
    path: "{{ archive_file }}"
  register: output
  when:
    - archive_file is defined
    - archive_file is string

- name: "Set fact for restore if archive_file exists"
  set_fact:
    restore: true
  when:
    - archive_file is defined
    - archive_file is string
    - output.stat.exists
    - output.stat.isreg
