---
# RedHat tasks file for ansible-role-suricata

- name: "Install the EPEL Repository (yum)"
  yum:
    name: "epel-release"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Install the EPEL Repository (dnf)"
  dnf:
    name: "epel-release"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Install the copr plugin for yum"
  yum:
    name: "yum-plugin-copr"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Install the dnf core plugins (dnf)"
  dnf:
    name: "dnf-plugins-core"
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Enable Suricata Packages via copr (yum - Standard)"
  shell: yum -y copr enable @oisf/suricata-{{ version }}
  when:
    - not proxy | bool
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Enable Suricata Packages via copr (yum - Proxy)"
  shell: yum -y copr enable @oisf/suricata-{{ version }}
  environment:
    http_proxy: "{{ proxy_protocol }}://{{ proxy_username }}@{{ proxy_password }}/{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_protocol }}://{{ proxy_username }}@{{ proxy_password }}/{{ proxy_host }}:{{ proxy_port }}"
  when:
    - proxy | bool
    - ansible_facts['pkg_mgr'] == 'yum'

- name: "Enable Suricata Packages via copr (dnf - Standard)"
  shell: dnf -y copr enable @oisf/suricata-{{ version }}
  when:
    - not proxy | bool
    - ansible_facts['pkg_mgr'] == 'dnf'

- name: "Enable Suricata Packages via copr (dnf - Proxy)"
  shell: dnf -y copr enable @oisf/suricata-{{ version }}
  environment:
    http_proxy: "{{ proxy_protocol }}://{{ proxy_username }}@{{ proxy_password }}/{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_protocol }}://{{ proxy_username }}@{{ proxy_password }}/{{ proxy_host }}:{{ proxy_port }}"
  when:
    - proxy | bool
    - ansible_facts['pkg_mgr'] == 'dnf'
