---
# Restore tasks file for ansible-role-suricata

- name: "Collect list of Suricata systemd unit files"
  find:
    paths: /usr/lib/systemd/system
    patterns: 'ids*,suricata*'
    file_type: file
  register: output

- name: "Set fact for found Suricata systemd unit files"
  set_fact:
    systemd_services: >-
      {{ output.files
         | map(attribute='path')
         | map('basename')
         | reject('equalto', 'suricata.service')
         | list
      }}

- debug:
    var: systemd_services
