---
# Rocky Linux tasks file for ansible-role-suricata

- name: "Install the EPEL Repository"
  dnf:
    name: "epel-release"
    state: present

- name: "Install the dnf core plugins"
  dnf:
    name: "dnf-plugins-core"
    state: present

- name: "Enable Suricata Packages via copr"
  shell: dnf -y copr enable @oisf/suricata-7.0

- name: "Install Suricata (dnf)"
  dnf:
    name: "suricata"
    state: present
