---
# Rocky Linux tasks file for ansible-role-suricata

- name: "Install the EPEL Repository"
  dnf:
    name: "epel-release"
    state: present

- name: "Install the dnf core plugins"
  dnf:
    name: "dnf-plugins-core"
    state: present

- name: "Check if Suricata copr repository enabled"
  shell: dnf copr list --enabled
  warn: false
  register: copr
  ignore_errors: true

- name: "Enable Suricata Packages via copr (Standard)"
  shell: dnf -y copr enable @oisf/suricata-{{ version }}
  args:
    warn: false
  when:
    - not proxy | bool
    - copr.stdout is not search('suricata')

- name: "Enable Suricata Packages via copr (Proxy)"
  shell: dnf -y copr enable @oisf/suricata-{{ version }}
  warn: false
  environment:
    http_proxy: "{{ proxy_protocol }}://{{ proxy_username }}:{{ proxy_password }}@{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_protocol }}://{{ proxy_username }}:{{ proxy_password }}@{{ proxy_host }}:{{ proxy_port }}"
  when:
    - proxy | bool
    - copr.stdout is not search('suricata')
